/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTodayRouteImport } from './routes/_authenticated/dashboard/today'
import { Route as AuthenticatedDashboardTasksRouteImport } from './routes/_authenticated/dashboard/tasks'
import { Route as AuthenticatedDashboardPreferencesRouteImport } from './routes/_authenticated/dashboard/preferences'
import { Route as AuthenticatedDashboardNotesRouteImport } from './routes/_authenticated/dashboard/notes'
import { Route as AuthenticatedDashboardEnergyRouteImport } from './routes/_authenticated/dashboard/energy'
import { Route as AuthenticatedDashboardEmailsRouteImport } from './routes/_authenticated/dashboard/emails'
import { Route as AuthenticatedDashboardDumpRouteImport } from './routes/_authenticated/dashboard/dump'
import { Route as AuthenticatedDashboardDisplayRouteImport } from './routes/_authenticated/dashboard/display'
import { Route as AuthenticatedDashboardCheckRouteImport } from './routes/_authenticated/dashboard/check'
import { Route as AuthenticatedDashboardCalendarRouteImport } from './routes/_authenticated/dashboard/calendar'
import { Route as AuthenticatedDashboardAgentRouteImport } from './routes/_authenticated/dashboard/agent'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTodayRoute =
  AuthenticatedDashboardTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTasksRoute =
  AuthenticatedDashboardTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPreferencesRoute =
  AuthenticatedDashboardPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotesRoute =
  AuthenticatedDashboardNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEnergyRoute =
  AuthenticatedDashboardEnergyRouteImport.update({
    id: '/energy',
    path: '/energy',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmailsRoute =
  AuthenticatedDashboardEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDumpRoute =
  AuthenticatedDashboardDumpRouteImport.update({
    id: '/dump',
    path: '/dump',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDisplayRoute =
  AuthenticatedDashboardDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCheckRoute =
  AuthenticatedDashboardCheckRouteImport.update({
    id: '/check',
    path: '/check',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarRoute =
  AuthenticatedDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentRoute =
  AuthenticatedDashboardAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/check': typeof AuthenticatedDashboardCheckRoute
  '/dashboard/display': typeof AuthenticatedDashboardDisplayRoute
  '/dashboard/dump': typeof AuthenticatedDashboardDumpRoute
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/dashboard/preferences': typeof AuthenticatedDashboardPreferencesRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/dashboard/today': typeof AuthenticatedDashboardTodayRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/check': typeof AuthenticatedDashboardCheckRoute
  '/dashboard/display': typeof AuthenticatedDashboardDisplayRoute
  '/dashboard/dump': typeof AuthenticatedDashboardDumpRoute
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/dashboard/preferences': typeof AuthenticatedDashboardPreferencesRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/dashboard/today': typeof AuthenticatedDashboardTodayRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/_authenticated/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/_authenticated/dashboard/check': typeof AuthenticatedDashboardCheckRoute
  '/_authenticated/dashboard/display': typeof AuthenticatedDashboardDisplayRoute
  '/_authenticated/dashboard/dump': typeof AuthenticatedDashboardDumpRoute
  '/_authenticated/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/_authenticated/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/_authenticated/dashboard/notes': typeof AuthenticatedDashboardNotesRoute
  '/_authenticated/dashboard/preferences': typeof AuthenticatedDashboardPreferencesRoute
  '/_authenticated/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/_authenticated/dashboard/today': typeof AuthenticatedDashboardTodayRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/dashboard/agent'
    | '/dashboard/calendar'
    | '/dashboard/check'
    | '/dashboard/display'
    | '/dashboard/dump'
    | '/dashboard/emails'
    | '/dashboard/energy'
    | '/dashboard/notes'
    | '/dashboard/preferences'
    | '/dashboard/tasks'
    | '/dashboard/today'
    | '/dashboard/'
    | '/api/oauth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/dashboard/agent'
    | '/dashboard/calendar'
    | '/dashboard/check'
    | '/dashboard/display'
    | '/dashboard/dump'
    | '/dashboard/emails'
    | '/dashboard/energy'
    | '/dashboard/notes'
    | '/dashboard/preferences'
    | '/dashboard/tasks'
    | '/dashboard/today'
    | '/dashboard'
    | '/api/oauth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/dashboard/agent'
    | '/_authenticated/dashboard/calendar'
    | '/_authenticated/dashboard/check'
    | '/_authenticated/dashboard/display'
    | '/_authenticated/dashboard/dump'
    | '/_authenticated/dashboard/emails'
    | '/_authenticated/dashboard/energy'
    | '/_authenticated/dashboard/notes'
    | '/_authenticated/dashboard/preferences'
    | '/_authenticated/dashboard/tasks'
    | '/_authenticated/dashboard/today'
    | '/_authenticated/dashboard/'
    | '/api/oauth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/today': {
      id: '/_authenticated/dashboard/today'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof AuthenticatedDashboardTodayRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tasks': {
      id: '/_authenticated/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AuthenticatedDashboardTasksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/preferences': {
      id: '/_authenticated/dashboard/preferences'
      path: '/preferences'
      fullPath: '/dashboard/preferences'
      preLoaderRoute: typeof AuthenticatedDashboardPreferencesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notes': {
      id: '/_authenticated/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof AuthenticatedDashboardNotesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/energy': {
      id: '/_authenticated/dashboard/energy'
      path: '/energy'
      fullPath: '/dashboard/energy'
      preLoaderRoute: typeof AuthenticatedDashboardEnergyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/emails': {
      id: '/_authenticated/dashboard/emails'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof AuthenticatedDashboardEmailsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/dump': {
      id: '/_authenticated/dashboard/dump'
      path: '/dump'
      fullPath: '/dashboard/dump'
      preLoaderRoute: typeof AuthenticatedDashboardDumpRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/display': {
      id: '/_authenticated/dashboard/display'
      path: '/display'
      fullPath: '/dashboard/display'
      preLoaderRoute: typeof AuthenticatedDashboardDisplayRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/check': {
      id: '/_authenticated/dashboard/check'
      path: '/check'
      fullPath: '/dashboard/check'
      preLoaderRoute: typeof AuthenticatedDashboardCheckRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendar': {
      id: '/_authenticated/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agent': {
      id: '/_authenticated/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof AuthenticatedDashboardAgentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAgentRoute: typeof AuthenticatedDashboardAgentRoute
  AuthenticatedDashboardCalendarRoute: typeof AuthenticatedDashboardCalendarRoute
  AuthenticatedDashboardCheckRoute: typeof AuthenticatedDashboardCheckRoute
  AuthenticatedDashboardDisplayRoute: typeof AuthenticatedDashboardDisplayRoute
  AuthenticatedDashboardDumpRoute: typeof AuthenticatedDashboardDumpRoute
  AuthenticatedDashboardEmailsRoute: typeof AuthenticatedDashboardEmailsRoute
  AuthenticatedDashboardEnergyRoute: typeof AuthenticatedDashboardEnergyRoute
  AuthenticatedDashboardNotesRoute: typeof AuthenticatedDashboardNotesRoute
  AuthenticatedDashboardPreferencesRoute: typeof AuthenticatedDashboardPreferencesRoute
  AuthenticatedDashboardTasksRoute: typeof AuthenticatedDashboardTasksRoute
  AuthenticatedDashboardTodayRoute: typeof AuthenticatedDashboardTodayRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAgentRoute: AuthenticatedDashboardAgentRoute,
    AuthenticatedDashboardCalendarRoute: AuthenticatedDashboardCalendarRoute,
    AuthenticatedDashboardCheckRoute: AuthenticatedDashboardCheckRoute,
    AuthenticatedDashboardDisplayRoute: AuthenticatedDashboardDisplayRoute,
    AuthenticatedDashboardDumpRoute: AuthenticatedDashboardDumpRoute,
    AuthenticatedDashboardEmailsRoute: AuthenticatedDashboardEmailsRoute,
    AuthenticatedDashboardEnergyRoute: AuthenticatedDashboardEnergyRoute,
    AuthenticatedDashboardNotesRoute: AuthenticatedDashboardNotesRoute,
    AuthenticatedDashboardPreferencesRoute:
      AuthenticatedDashboardPreferencesRoute,
    AuthenticatedDashboardTasksRoute: AuthenticatedDashboardTasksRoute,
    AuthenticatedDashboardTodayRoute: AuthenticatedDashboardTodayRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
